require("dotenv").config();
const fs = require("fs");
const path = require("path");
const mongoose = require("mongoose");
const User = require("../models/User");
const { hashPassword } = require("../utils/password");
const { createPublicId } = require("../utils/publicId");

const CREDENTIALS_MD = path.resolve(__dirname, "../../ADMIN_CREDENTIALS.md");

function writeCredentialsDoc({ email, name, password, adminUrl }) {
  const body = `# Admin credentials (local dev)

Generated by \`npm run seed:admin\` in \`coupondealz/server\`.

| Field | Value |
|-------|-------|
| Admin login URL | ${adminUrl} |
| Email | \`${email}\` |
| Password | \`${password}\` |
| Display name | ${name} |
| Role | \`admin\` |

## How to sign in

1. Start API: \`cd coupondealz/server && npm run dev\` (port **5000** by default).
2. Start admin UI: \`cd coupondealz/admin && npm start\` (port **3001**).
3. Open **${adminUrl}** and sign in with the email and password above.

## Re-seed or change password

Set optional env vars in \`coupondealz/server/.env\`, then run:

\`\`\`bash
cd coupondealz/server
npm run seed:admin
\`\`\`

| Variable | Default |
|----------|---------|
| \`ADMIN_SEED_EMAIL\` | \`admin@coupondealz.com\` |
| \`ADMIN_SEED_PASSWORD\` | \`Admin@12345\` |
| \`ADMIN_SEED_NAME\` | \`CouponDealz Admin\` |
| \`ADMIN_LOGIN_URL\` | \`http://localhost:3001/login\` |

> **Security:** Use these credentials for local development only. Do not commit production passwords.
`;

  fs.writeFileSync(CREDENTIALS_MD, body, "utf8");
  console.log(`Wrote ${CREDENTIALS_MD}`);
}

async function run() {
  if (!process.env.MONGO_URL) {
    console.error("Set MONGO_URL in server/.env");
    process.exit(1);
  }

  const email = String(process.env.ADMIN_SEED_EMAIL || "admin@coupondealz.com")
    .toLowerCase()
    .trim();
  const name = String(process.env.ADMIN_SEED_NAME || "CouponDealz Admin").trim();
  const password = String(process.env.ADMIN_SEED_PASSWORD || "Admin@12345");
  const adminUrl = String(
    process.env.ADMIN_LOGIN_URL || "http://localhost:3001/login"
  ).trim();

  if (password.length < 8) {
    console.error("ADMIN_SEED_PASSWORD must be at least 8 characters");
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGO_URL);

  try {
    const existing = await User.findOne({ email }).select("_id email role");
    const passwordHash = await hashPassword(password);

    if (!existing) {
      await User.create({
        publicId: createPublicId("u"),
        email,
        name,
        role: "admin",
        passwordHash,
      });
      console.log(`Admin user created: ${email}`);
    } else {
      await User.updateOne(
        { _id: existing._id },
        { $set: { name, role: "admin", passwordHash } }
      );
      console.log(`Admin user updated: ${email}`);
    }

    writeCredentialsDoc({ email, name, password, adminUrl });
    console.log(`Login: ${adminUrl}`);
    console.log(`Email: ${email}`);
    console.log(`Password: ${password}`);
  } finally {
    await mongoose.disconnect();
  }
}

run().catch((err) => {
  console.error("Admin seed failed:", err.message);
  process.exit(1);
});
